### ISSUE TITLE
[Bug]: android:hardwareAccelerated="false" only shows half a screen, while the other half is the phone's homescreen

### ISSUE THREAD

**Issue by soemarko** [apivideo/api.video-reactnative-live-stream#83] opened 2024-05-25 08:58 UTC
### Version

v2.0.0

### Which operating systems have you used?

- [X] Android
- [ ] iOS

### Environment that reproduces the issue

Android 13 (both samsung and asus ROG)

### Is it reproducible in the example application?

Yes

### RTMP Server

IVS

### Reproduction steps

```
      <ApiVideoLiveStreamView
          style={styles.livestream}
          ref={livestreamRef}
          camera={isFrontCamera ? 'front' : 'back'}
          enablePinchedZoom={false}
          video={{
            fps: 30,
            resolution: '480p',
            bitrate: 1 * 1024 * 1024, // # 1 Mbps
          }}
          audio={{
            bitrate: 128000,
            sampleRate: 44100,
            isStereo: true,
          }}
          isMuted={false}
          onConnectionSuccess={() => {
            //do what you want
            console.log('on connection success');
            streamStarted();
            setIsStreaming(true);
            setIsStreamStarting(false);
          }}
          onConnectionFailed={() => {
            //do what you want
            console.log('on connection failed');
            setIsStreaming(false);
          }}
          onDisconnect={() => {
            //do what you want
            console.log('on disconnect');
            setIsStreaming(false);
          }}
        />
```

### Expected result

Full camera screen

### Actual result

![WhatsApp Image 2024-05-24 at 15 59 08](https://github.com/apivideo/api.video-reactnative-live-stream/assets/381585/265f650c-2a0b-488f-9990-b8eaeaa83097)

Just half a screen, and squished up. The bottom half is the phone's homescreen, but all my other components still there. Like the chat text input.

### Additional context

React Native 0.74.1

**Comment by ThibaultBee** [comment] 2024-05-29 08:13
Hi,

Have you tried running the code in https://github.com/apivideo/api.video-reactnative-live-stream/tree/main/example?
Have made any constraint to the view?
It is going to be a tricky issue.
Could you share the logcat? I am not sure to find anything relevant but it might help :)

**Comment by soemarko** [comment] 2024-05-30 08:40
It's working fine on the example app. But when I copied across the `<ApiVideoLiveStreamView />` (some values need adjustment),.. I'm getting even smaller view port

<img width="570" alt="Screenshot 2024-05-30 at 3 34 47 PM" src="https://github.com/apivideo/api.video-reactnative-live-stream/assets/381585/db4903f7-fd26-4148-9020-bf7826dbce50">

> Could you share the logcat?

How do I get that? I've tried `$ adb logcat *:S ReactNative:V ReactNativeJS:V`, but just getting this as result.
`zsh: no matches found: *:S`

**Comment by ThibaultBee** [comment] 2024-06-04 08:33
Just `adb logcat` and I will filter the logs.

**Comment by ThibaultBee** [comment] 2024-06-07 07:48
Is there something in the `style` that would make this behavior?

**Comment by soemarko** [comment] 2024-06-07 08:58
I doubt it, since the background is the phone's dashboard, not anything from RN. But here's my whole style

```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0
  },
  livestream: {
    flex: 1,
    backgroundColor: 'black',
    alignSelf: 'stretch',
  },
  imageContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 200,
    height: 200,
    flexDirection: 'row',
    backgroundColor: 'orange',
    opacity: 0.8
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 80,
    alignSelf: 'center',
    flexDirection: 'row'
  }
});
```

Give me some time for the logcat, I'm currently on a different branch with nodemediaclient, I prefer if I could use this though, since I can get a snapshot of the preview screen, at least on iOS.

**Comment by soemarko** [comment] 2024-06-07 09:02
Actually, here's the whole file: https://gist.github.com/soemarko/b3139d3dbf6d649ccfbbe9fab2774261

I don't think I'm doing anything crazy.

**Comment by ThibaultBee** [comment] 2024-06-07 09:58
Could you try to modify the example so we can easily reproduce it in our environment?

**Comment by soemarko** [comment] 2024-06-09 07:31
I've found the source problem, in my `android/app/src/main/AndroidManifest.xml` file I've added `android:hardwareAccelerated="false"`. I honestly can't remember why. But that causes this problem.

Feel free to close this issue if you don't consider this a bug (although nodemediaclient is working fine). Now I need to investigate why I added that at some point in my project.

**Comment by ThibaultBee** [comment] 2024-06-10 08:40
oh. As the `View` is a `SurfaceView` (which rely on androidx.camera:camera-viewfinder package), I don't really understand why `hardwareAccelerated` has an impact on it.
But you are not the only one: https://stackoverflow.com/questions/59850963/android-camerax-java-wrong-preview-orientation

**Comment by soemarko** [comment] 2024-06-12 08:33
> Now I need to investigate why I added that at some point in my project.

I've figured this part out, the app is quite "animated", and with hardware acceleration the app is crashy when user taps taps taps quickly. Disabling it just solves a lot of weird crashes that never happens on iOS.

Anyway, as mentioned, feel free to close this. I'll change the title to better reflect the issue.

**Comment by ThibaultBee** [comment] 2024-07-12 09:21
Closing because it is application related.

**Closed by ThibaultBee** 2024-07-12 09:21 UTC
Labels: bug
