### ISSUE TITLE
gop, keyframes

### ISSUE THREAD

**Issue by nikitapilgrim** [apivideo/api.video-reactnative-live-stream#42] opened 2022-11-06 16:42 UTC
Can I change this setting (keyframes)? I need to set it from 2-8 sec

**Comment by ThibaultBee** [comment] 2022-11-07 07:30
Hi,
There is no way to set the gop size in the API yet.
Why would you need these requirements?

**Comment by nikitapilgrim** [comment] 2022-11-08 05:46
your library can be used for a custom server. It would be great if you could pass more options

**Comment by ThibaultBee** [comment] 2022-11-08 08:47
yeah, but an increase of the gop means that if you lost a packet at the beginning of the gop (packet loss is likely to happen in live streaming), the live stream will be altered for up to X seconds which can be a long period. 8 seconds is a long period for a viewer.
So, we don't understand why you require to increase gop size. We need to understand the use case and the reason behind this before adding such settings.

**Comment by nikitapilgrim** [comment] 2022-11-08 13:17
https://www.facebook.com/help/1534561009906955?cms_id=1534561009906955&published_only=true
https://support.google.com/youtube/answer/2853702?hl=en
they recommend a minimum of 2 seconds everywhere. I can't use this library with different services right now because I can't change the keyframe to at least 2 seconds

**Comment by nikitapilgrim** [comment] 2022-11-08 13:19
I would be very grateful if you could implement this or suggest an alternative

**Comment by ThibaultBee** [comment] 2022-11-08 16:36
A gop of 2s is a recommended settings for these platform not a requirement. Right? For which services are you stuck?

**Comment by nikitapilgrim** [comment] 2022-11-08 16:37
I have this problem with cloudflare live stream

**Comment by ThibaultBee** [comment] 2023-01-05 09:55
Hi,

A parameter `gopDuration` has been added to the native dependencies:
- https://github.com/apivideo/api.video-ios-live-stream
- https://github.com/apivideo/api.video-android-live-stream

It will be integrated in the RN part soon.

**Comment by ThibaultBee** [comment] 2023-01-06 15:23
I just added a `gopDuration` param in the `video` object.
Could you that this issue is fixed in the `main` branch?

**Comment by nikitapilgrim** [comment] 2023-01-07 10:23
> I just added a `gopDuration` param in the `video` object.
> Could you that this issue is fixed in the `main` branch?
Yes it works. Only for some reason there is no sound :( But the video shows as it should

**Comment by nikitapilgrim** [comment] 2023-01-07 15:41
> Stream Live only supports H.264 video and AAC audio codecs as inputs. This requirement does not apply to inputs that are relayed to Stream Connect outputs. Stream Live supports ADTS but does not presently support LATM.

Can you tell me if this could be a problem?

**Comment by ThibaultBee** [comment] 2023-01-09 07:56
> > I just added a `gopDuration` param in the `video` object.
> > Could you that this issue is fixed in the `main` branch?
> 
> Yes it works. Only for some reason there is no sound :( But the video shows as it should

On Android or iOS?



> > Stream Live only supports H.264 video and AAC audio codecs as inputs. This requirement does not apply to inputs that are relayed to Stream Connect outputs. Stream Live supports ADTS but does not presently support LATM.
> 
> Can you tell me if this could be a problem?

No, it should not.

**Comment by ThibaultBee** [comment] 2023-01-09 08:04
The reason you have issue with the audio stream is that the audio is muted by default due to a regression. Thanks for noticing.

**Comment by nikitapilgrim** [comment] 2023-01-11 06:09
Yes there is sound now. And the camera starts quickly

**Comment by ThibaultBee** [comment] 2023-01-11 10:32
This should be fixed in v1.2.2.

**Closed by ThibaultBee** 2023-01-11 10:32 UTC
Labels: enhancement
