### ISSUE TITLE
Width and Height of the LivestreamView looks weird

### ISSUE THREAD

**Issue by OsmonKida** [apivideo/api.video-reactnative-live-stream#12] opened 2022-01-17 14:26 UTC
So the LivestreamView component doesn't take the whole screen for some reason
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45068007/149787231-e57f2c2c-e66b-486e-8e5d-a76a5e4f5c9c.png)
And after I start the stream the height changes to
![MicrosoftTeams-image_2](https://user-images.githubusercontent.com/45068007/149787469-b7c7061e-6dde-4307-af52-4a256477467d.jpeg)

**Comment by ThibaultBee** [comment] 2022-01-18 07:49
Hello,

I guess you do have black lines because the view respects the camera aspect ratio (16/9) (and not your screen).
What video framing do you expect?
- Pan and scan
- Fit to view size (anamorphic)
- Letterbox (what we have today)

However the size change seems to be an issue. Does it happen on Android or on iOS? Did you reproduce it with our example?

Best regards,
Thibault

**Comment by OsmonKida** [comment] 2022-01-18 09:29
I was hoping to fit the whole screen, I think it is Fit to view size. It happens on Android and yeah I reproduced it with the example and it is the same issue.

Thank you!

**Comment by ThibaultBee** [comment] 2022-01-20 12:52
The fit to view will stretch or compress the camera preview. Are you sure you want this?
Anyway, we will rewrite this library in a near future. We will keep that in mind.

**Comment by ThibaultBee** [comment] 2022-08-08 12:32
The preview has been changed since January -> Closing it for now.
If you still face the same issue, please reopen it.

**Closed by ThibaultBee** 2022-08-08 12:32 UTC
